version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: projeto_3_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  django-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: projeto_3_web
    volumes:
      - ./projeto_cad:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
