# Generated by Django 5.1.1 on 2024-10-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50)),
                ("empresa", models.CharField(max_length=150)),
                ("segmento", models.CharField(max_length=100)),
                ("contato", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("telefone_2", models.CharField(max_length=20)),
                ("cep", models.IntegerField(max_length=8)),
                ("rua", models.CharField(max_length=150)),
                ("numero_end", models.IntegerField(max_length=8)),
                ("bairro", models.CharField(max_length=120)),
                ("complemento", models.CharField(max_length=120)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("email", models.EmailField(max_length=254)),
                ("instagram", models.CharField(max_length=100)),
                ("cnpj", models.CharField(max_length=18)),
                ("qtd_lojas", models.IntegerField()),
                ("prox_contato", models.DateTimeField(blank=True, null=True)),
                ("primeiro_contato", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Observacoes",
            fields=[
                ("id_observacao", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.TextField()),
                ("data_observacao", models.DateTimeField(auto_now_add=True)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="app_cad_clientes.clientes",
                    ),
                ),
            ],
        ),
    ]
